version: '2'
services:
  media-server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./media:/app/media
    ports:
      - 8000:8000
      - 8080:8080
      - 1935:1935
    command: ['yarn', 'start:dev']
    environment:
      PUBLISH_START_NOTIFY_URL: ''
      PUBLISH_STOP_NOTIFY_URL: ''
    networks:
      - app-network
    links:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge